name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test AnimalAdoption.Web.Portal.UnitTests/AnimalAdoption.Web.Portal.UnitTests.csproj --no-build --verbosity normal
    - name: publish the artifact
      run: dotnet publish AnimalAdoption.sln -o ${{ github.workspace }}/artifact
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        # Artifact name
        name: artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: ${{ github.workspace }}/artifact/*
        # The desired behavior if no files are found using the provided path.
    - name: Deploy artifact to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: buffaloWebApp-Dev
        publish-profile: ${{ secrets.PUBLISH_PROFILE_SETTINGS }}
        package: ${{ github.workspace }}/artifact
    - name: Notification for build failure
      uses: jdcargile/ms-teams-notification@v1.3
      if: failure()
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
        notification-summary: BUILD FAILED
        notification-color: 'dc3545 '
    - name: Notification for build success
      uses: jdcargile/ms-teams-notification@v1.3
      if: success()
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
        notification-summary: BUILD SUCCEEDED
        notification-color: '28a745'
    
