name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test AnimalAdoption.Web.Portal.UnitTests/AnimalAdoption.Web.Portal.UnitTests.csproj --no-build --verbosity normal
    - name: publish the artifact
      run: dotnet publish AnimalAdoption.sln -o ${{ github.workspace }}/artifact
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        # Artifact name
        name: artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: ${{ github.workspace }}/artifact/*
        # The desired behavior if no files are found using the provided path.
    - name: Az login action
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    # - name: Azure App Service Settings
    #   uses: Azure/appservice-settings@v1
    #   with:
    #     app-name: buffaloWebApp-Dev
    #     app-settings-json: '${{ secrets.APP_SETTINGS }}'
    - name: Deploy artifact to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: buffaloWebApp-Dev
        package: ${{ github.workspace }}/artifact
        startup-command: "dotnet AnimalAdoption.Web.Portal.dll"
    
