name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_dev:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test AnimalAdoption.Web.Portal.UnitTests/AnimalAdoption.Web.Portal.UnitTests.csproj --no-build --verbosity normal
    - name: publish the artifact
      run: dotnet publish AnimalAdoption.sln -o ${{ github.workspace }}/artifact
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        # Artifact name
        name: artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: ${{ github.workspace }}/artifact/*
        # The desired behavior if no files are found using the provided path.
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v3
      with:
        name: artifact
        path: ${{ github.workspace }}/artifact
    - name: Az login action
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
     # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./deploy.bicep
        parameters: "tenantGuid=ab5eb3d0-6067-40ee-b4c0-a2ce05dbf039 appServicePlanName=MyPlan keyVaultName=privatekey02 webAppName=buffaloWebApp-Prod resourceGroupServicePrincipalManagedApplicationObjectId=60b314e1-8a8c-48c0-be8b-20742f605c40"
        failOnStdErr: false
    - uses: Azure/get-keyvault-secrets@v1
      with:
        keyvault: "privatekey01" # name of key vault in Azure portal
        secrets: 'GlobalPassword'  # comma separated list of secret keys to fetch from key vault 
      id: myGetSecretAction
    - name: Azure App Service Settings
      uses: Azure/appservice-settings@v1
      with:
        app-name: buffaloWebApp-Prod
        app-settings-json: '[ { "name": "GlobalPassword", "value": "${{ env.GlobalPassword }}", "slotSetting": false } ]'
    - name: Deploy artifact to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: buffaloWebApp-Prod
        package: ${{ github.workspace }}/artifact
        startup-command: "dotnet AnimalAdoption.Web.Portal.dll"
