- name: List out directory contents
  run: |
      echo "Listing the contents of the GitHub workspace directory"
      ls ${{ github.workspace }}

      echo "Recursively listing all contents of the current directory"
      ls -R